const SUPABASE_URL="https://oabjxsclanvgmvnezabj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_Wccb86Hdfbxwx1tj0ciPDg_aRv8yqje";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const demo=[{id:"d1",name:"Pack Gaming — démo",category:"Gaming",price:5000,image:"🎮",available:true},{id:"d2",name:"Offre eFootball — démo",category:"eFootball",price:3000,image:"⚽",available:true},{id:"d3",name:"Produit digital — démo",category:"Digital",price:2500,image:"💻",available:true},{id:"d4",name:"Pack Premium — démo",category:"Premium",price:7500,image:"⭐",available:true}];
let products=[],cart=JSON.parse(localStorage.getItem("mhd_cart")||"{}"),active="Tous",session=null,isAdmin=false;
const $=x=>document.querySelector(x),money=n=>new Intl.NumberFormat("fr-FR").format(n)+" FCFA";
function saveCart(){localStorage.setItem("mhd_cart",JSON.stringify(cart));count()}
function go(id){if(id==="admin"&&!isAdmin){alert("Accès réservé à l’administrateur.");go("compte");return}document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");scrollTo(0,0);if(id==="admin")renderAdmin()}
document.addEventListener("click",e=>{let b=e.target.closest("[data-go]");if(b)go(b.dataset.go)});
function cats(){return["Tous",...new Set(products.map(p=>p.category))]}
function renderCats(){$("#categories").innerHTML=cats().map(c=>`<button class="chip" onclick="setCat(${JSON.stringify(c)})">${c}</button>`).join("")}
function card(p){let im=(p.image||"").startsWith("http")?`<img src="${p.image}" alt="">`:`<span>${p.image||"📦"}</span>`;return`<article class="card"><div class="product-image">${im}</div><h3>${p.name}</h3><div class="price">${money(p.price)}</div><p class="${p.available?"available":"unavailable"}">${p.available?"Disponible":"Indisponible"}</p><button class="primary" ${p.available?"":"disabled"} onclick="add('${String(p.id).replace(/'/g,"\\'")}')">${p.available?"Ajouter":"Indisponible"}</button></article>`}
function render(){let q=( $("#search")?.value||"").toLowerCase();let arr=products.filter(p=>(active==="Tous"||p.category===active)&&(!q||p.name.toLowerCase().includes(q)));$("#products").innerHTML=arr.map(card).join("")||"<p>Aucun produit trouvé.</p>";$("#homeProducts").innerHTML=products.slice(0,4).map(card).join("");renderCats()}
function setCat(c){active=c;render()}
function add(id){cart[id]=(cart[id]||0)+1;saveCart();renderCart();go("panier")}
function change(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];saveCart();renderCart()}
function renderCart(){let ids=Object.keys(cart),total=0;if(!ids.length){$("#cart").innerHTML='<div class="panel"><p>Ton panier est vide.</p><button class="primary" data-go="boutique">Voir la boutique</button></div>';return}let rows=ids.map(id=>{let p=products.find(x=>String(x.id)===String(id)),q=cart[id];if(!p)return"";total+=p.price*q;return`<div class="admin-item"><div class="grow"><b>${p.name}</b><br>${money(p.price)}</div><button onclick="change('${id}',-1)">−</button><b>${q}</b><button onclick="change('${id}',1)">+</button></div>`}).join("");$("#cart").innerHTML=rows+`<h2>Total : ${money(total)}</h2><button class="primary" onclick="orderWhatsApp()">Commander sur WhatsApp</button>`}
function orderWhatsApp(){let text="Bonjour MHD SHOP, je souhaite commander :%0A";Object.keys(cart).forEach(id=>{let p=products.find(x=>String(x.id)===String(id));if(p)text+=`- ${encodeURIComponent(p.name)} x${cart[id]}%0A`});location.href=`https://wa.me/221787488199?text=${text}`}
function count(){$("#cartCount").textContent=Object.values(cart).reduce((a,b)=>a+b,0)}
function authHTML(){if(!session)return`<p>Connecte-toi pour gérer ton compte.</p><button class="primary" id="googleLogin">Continuer avec Google</button><hr><label>Email</label><input id="email" type="email" placeholder="ton@email.com"><label>Mot de passe</label><input id="password" type="password" placeholder="••••••••"><button class="primary" id="emailLogin">Se connecter</button><button id="emailSignup">Créer un compte</button><p id="authMsg"></p>`;return`<p><b>${session.user.email||"Compte connecté"}</b></p>${isAdmin?'<p class="available">Administrateur autorisé ✅</p>':''}<button id="logout">Se déconnecter</button>`}
async function renderAuth(){$("#authPanel").innerHTML=authHTML();if(!session){$("#googleLogin").onclick=googleLogin;$("#emailLogin").onclick=()=>emailAuth(false);$("#emailSignup").onclick=()=>emailAuth(true)}else $("#logout").onclick=logout}
async function googleLogin(){const{error}=await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:"https://hjdnrzd792-star.github.io/MHD-shop/"}});if(error)alert(error.message)}
async function emailAuth(signup){let email=$("#email").value.trim(),password=$("#password").value;if(!email||password.length<6){$("#authMsg").textContent="Entre un email et un mot de passe d’au moins 6 caractères.";return}let r=signup?await db.auth.signUp({email,password,options:{emailRedirectTo:"https://hjdnrzd792-star.github.io/MHD-shop/"}}):await db.auth.signInWithPassword({email,password});if(r.error){$("#authMsg").textContent=r.error.message;return}$("#authMsg").textContent=signup?"Compte créé. Vérifie ton email si Supabase le demande.":"Connexion réussie."}
async function logout(){await db.auth.signOut();go("accueil")}
async function refreshUser(){let r=await db.auth.getSession();session=r.data.session;isAdmin=false;if(session){let p=await db.from("profiles").select("role").eq("id",session.user.id).maybeSingle();isAdmin=p.data?.role==="admin"}$("#adminOpen").style.display=isAdmin?"flex":"none";await renderAuth()}
async function loadProducts(){let r=await db.from("products").select("id,name,category,price,image,available").order("created_at",{ascending:false});if(r.error){products=demo}else products=r.data?.length?r.data:demo;render();renderCart()}
async function renderAdmin(){if(!isAdmin)return;let r=await db.from("products").select("id,name,category,price,image,available").order("created_at",{ascending:false});let list=r.data||[];$("#adminProducts").innerHTML=list.map(p=>`<div class="admin-item"><div class="grow"><b>${p.name}</b><br>${p.category} · ${money(p.price)}<br><small class="${p.available?"available":"unavailable"}">${p.available?"Disponible":"Indisponible"}</small></div><button onclick="edit(${p.id})">✏️</button><button class="danger" onclick="del(${p.id})">🗑️</button></div>`).join("")||"<p>Aucun produit.</p>"}
function reset(){$("#editId").value="";$("#pName").value="";$("#pCategory").value="";$("#pPrice").value="";$("#pImage").value="";$("#pAvailable").value="true";$("#formTitle").textContent="Ajouter un produit"}
async function edit(id){let p=products.find(x=>x.id==id);if(!p){let r=await db.from("products").select("*").eq("id",id).single();p=r.data}if(!p)return;$("#editId").value=p.id;$("#pName").value=p.name;$("#pCategory").value=p.category;$("#pPrice").value=p.price;$("#pImage").value=p.image||"";$("#pAvailable").value=String(p.available);$("#formTitle").textContent="Modifier le produit"}
async function del(id){if(!confirm("Supprimer ce produit ?"))return;let r=await db.from("products").delete().eq("id",id);if(r.error)alert(r.error.message);else{await loadProducts();await renderAdmin()}}
$("#saveProduct").onclick=async()=>{let name=$("#pName").value.trim(),category=$("#pCategory").value.trim(),price=Number($("#pPrice").value);if(!name||!category||price<=0)return alert("Remplis le nom, la catégorie et le prix.");let id=$("#editId").value,obj={name,category,price,image:$("#pImage").value.trim()||"📦",available:$("#pAvailable").value==="true"};let r=id?await db.from("products").update(obj).eq("id",id):await db.from("products").insert(obj);if(r.error)alert(r.error.message);else{reset();await loadProducts();await renderAdmin()}}
$("#cancelEdit").onclick=reset;$("#adminExit").onclick=()=>go("accueil");$("#search").oninput=render;
async function boot(){await refreshUser();await loadProducts();count();db.auth.onAuthStateChange(()=>setTimeout(refreshUser,0))}boot();
