-- MHD SHOP V4 : à exécuter dans Supabase > SQL Editor
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null check (price > 0),
  image text,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can read available products" on public.products;
create policy "Public can read available products" on public.products
for select to anon, authenticated using (available = true or public.is_admin());

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products" on public.products
for insert to authenticated with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products" on public.products
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products" on public.products
for delete to authenticated using (public.is_admin());

insert into public.products (name,category,price,image,available)
select * from (values
 ('Pack Gaming — démo','Gaming',5000,'🎮',true),
 ('Offre eFootball — démo','eFootball',3000,'⚽',true),
 ('Produit digital — démo','Digital',2500,'💻',true),
 ('Pack Premium — démo','Premium',7500,'⭐',true)
) as v(name,category,price,image,available)
where not exists (select 1 from public.products);
